meta_title: "SWAPP - Connect with people through skill sharing!"
meta_description: "SWAPP is a platform to meet people with whom to share your skills. Based on your preferences, our system will offer you a list of people matching your interests and you’ll be able to interact with them through our chat. The rest is up to you! Join the community and start SWAPPing!"
meta_image: "meta_pic.png"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
