meta_title: "SWAPP - Connect with people through skill sharing!"
meta_description: "SWAPP is a platform to connect with other people with whom we share skills and intrests. Find new friends here!"
meta_image: "meta_pic.png"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
