meta_title: "SWAPP"
meta_description: "Connect with people through skill sharing!"
meta_image: "meta_pic.png"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
